# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-14 11:23
from __future__ import unicode_literals

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeSpot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporters_ids', models.CharField(default='', max_length=20000)),
                ('last_report_time', models.CharField(default='', max_length=200)),
                ('parking_address', models.CharField(max_length=200)),
                ('street_name', models.CharField(max_length=200)),
                ('parking_address_lat', models.CharField(max_length=2000)),
                ('parking_address_lng', models.CharField(max_length=2000)),
                ('parking_rank', models.IntegerField(default=0)),
                ('is_verified', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('points', models.IntegerField(default=50)),
                ('rating', models.IntegerField(default=2)),
                ('is_blocked', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_id', models.IntegerField(default=-1)),
                ('seller_id', models.IntegerField(default=-1)),
                ('cost', models.IntegerField(default=10)),
                ('parking_time', models.CharField(default='', max_length=200)),
                ('status', models.CharField(default='available', max_length=200)),
                ('parking_rate', models.DecimalField(decimal_places=2, default=Decimal('0.0000'), max_digits=3)),
                ('target_address_lat', models.CharField(max_length=2000)),
                ('target_address_lng', models.CharField(max_length=2000)),
                ('parking_address', models.CharField(max_length=200)),
                ('parking_address_lat', models.CharField(max_length=2000)),
                ('parking_address_lng', models.CharField(max_length=2000)),
                ('pin_code', models.CharField(default='-1', max_length=2000)),
                ('parking_actual_rank', models.DecimalField(decimal_places=2, default=Decimal('0.0000'), max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.CharField(max_length=2000)),
                ('lng', models.CharField(max_length=2000)),
                ('hour', models.IntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=7, default=Decimal('0.0000'), max_digits=8)),
                ('date', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
