# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-22 13:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeSpot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporters_ids', models.CharField(default='', max_length=20000)),
                ('last_report_time', models.DateTimeField()),
                ('parking_address', models.CharField(max_length=200)),
                ('street_name', models.CharField(max_length=200)),
                ('parking_rank', models.IntegerField(default=0)),
                ('is_verified', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('points', models.IntegerField(default=50)),
                ('rating', models.IntegerField(default=2)),
                ('is_blocked', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_id', models.IntegerField(default=-1)),
                ('seller_id', models.IntegerField(default=-1)),
                ('cost', models.IntegerField(default=10)),
                ('parking_time', models.DateTimeField()),
                ('status', models.CharField(default='available', max_length=200)),
                ('parking_rate', models.DecimalField(decimal_places=3, default=-1, max_digits=3)),
                ('target_address', models.CharField(max_length=200)),
                ('parking_address', models.CharField(max_length=200)),
                ('pin_code', models.IntegerField(default=-1)),
            ],
        ),
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
