# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-31 11:03
from __future__ import unicode_literals

import datetime
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20171222_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='parking_address',
            field=models.CharField(max_length=200000),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='parking_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0000'), max_digits=3),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='parking_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(default='available', max_length=200000000),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='target_address',
            field=models.CharField(max_length=200000),
        ),
    ]
