# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-14 11:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_purchase_target_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='target_address',
        ),
    ]
