# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-14 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_remove_purchase_target_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='attempt_failure',
            field=models.IntegerField(default=0),
        ),
    ]
