# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-02 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20171231_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freespot',
            name='last_report_time',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='parking_address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='parking_time',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(default='available', max_length=200),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='target_address',
            field=models.CharField(max_length=200),
        ),
    ]
