# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-16 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_purchase_attempt_failure'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='num_reported',
            field=models.IntegerField(default=0),
        ),
    ]
