# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-02 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20180102_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='parking_address_lat',
            field=models.CharField(default='', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='parking_address_lng',
            field=models.CharField(default='', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='target_address_lat',
            field=models.CharField(default='', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='target_address_lng',
            field=models.CharField(default='', max_length=2000),
            preserve_default=False,
        ),
    ]
