# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-07 20:49
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20180102_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='freespot',
            name='parking_address_lat',
            field=models.CharField(default='', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='freespot',
            name='parking_address_lng',
            field=models.CharField(default='', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='parking_actual_rank',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0000'), max_digits=3),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='pin_code',
            field=models.CharField(default='-1', max_length=2000),
        ),
    ]
