# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-16 05:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_profile_num_reported'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='parking_address',
            field=models.CharField(default='Tel Aviv', max_length=200),
        ),
    ]
